name: Build and Release

on:
    push:
        branches:
            - "**"
        tags:
            - "*"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: bun-linux-x64
                      binary-name: puppycloud-linux
                    - os: macos-latest
                      target: bun-darwin-x64
                      binary-name: puppycloud-macos
                    - os: windows-latest
                      target: bun-windows-x64
                      binary-name: puppycloud-windows.exe
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build binary
              run: bun build src/main.ts --compile --outfile ${{ matrix.binary-name }} --target ${{ matrix.target }}

            - name: Upload artifact
              if: startsWith(github.ref, 'refs/tags/')
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.binary-name }}
                  path: ${{ matrix.binary-name }}

    release:
        if: startsWith(github.ref, 'refs/tags/')
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                path: artifacts

            - name: List files
              run: ls -R artifacts

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      artifacts/puppycloud-linux/puppycloud-linux
                      artifacts/puppycloud-macos/puppycloud-macos
                      artifacts/puppycloud-windows.exe/puppycloud-windows.exe